# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
    - id: check-toml
    - id: check-added-large-files
    - id: mixed-line-ending
      args:
        - "--fix=lf"
      exclude: "make.bat"
    - id: no-commit-to-branch
- repo: local
  hooks:
    - id: black
      name: black
      language: system
      entry: poetry run black
      types: [python]
    - id: flake8
      name: flake8
      language: system
      entry: poetry run flake8
      types: [python]
